services:
  - type: worker
    name: music-bot
    runtime: image
    image:
      url: python:3.10-slim
    buildCommand: pip install -r requirements.txt
    startCommand: python music_bot.py
    envVars:
      - key: API_ID
        value: 31427123
      - key: API_HASH
        value: 27b540811ee6d2423f86a779848515ee
      - key: BOT_TOKEN
        value: 8783739539:AAFPM95HIrSJQ-yoPtc-r8guZ-QJFgPymWA
      - key: ASSISTANT_SESSION
        value: EqjNDUzaEfECHJAkGV3IRxaeudjGHmTGYLNGUtBLWrFzx5hSzBXdGSP4afvkgj9G8gBvjVtN-GxRDftKR3Pes6XECYjV7iQ8EhCEFWYVo_fm_vO-S2GQ7Ih-R8KKlv7OpJv6zGd6Y8n3UjhQ1T6RNSrFk0vQBgfISrQAAAAGmRHBgAA
      - key: OWNER_ID
        sync: false
