services:
  - type: worker
    name: music-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python music_bot.py
    envVars:
      - key: API_ID
        value: 31427123
      - key: API_HASH
        value: 27b540811ee6d2423f86a779848515ee
      - key: BOT_TOKEN
        value: 8783739539:AAFPM95HIrSJQ-yoPtc-r8guZ-QJFgPymWA
      - key: ASSISTANT_SESSION
        value: BQHfijMAbjnzX4SbFoURqvXouZ41weK0LDyW_8LNdJrU9jHYfpimV4B-KK_hTeJBNTVEXqC4dHANRDuUrdhNgX675J6lm6Ny8mnPYVdLl_go643lkbMH21kVIrFMkS3v_vpC-04F7T8NtzCV3cCg8-IEjXNX0EhygHZ3qZJ5EQLEmze
      - key: OWNER_ID
        sync: false