services:
  - type: worker
    name: music-bot
    runtime: image
    image:
      url: python:3.10-slim
    buildCommand: pip install -r requirements.txt
    startCommand: python music_bot.py
    envVars:
      - key: API_ID
        value: 31427123
      - key: API_HASH
        value: 27b540811ee6d2423f86a779848515ee
      - key: BOT_TOKEN
        value: 8783739539:AAFPM95HIrSJQ-yoPtc-r8guZ-QJFgPymWA
      - key: ASSISTANT_SESSION
        value: BQHfijMAhGoy0E7GCe5gQSmdBtM3BEFfPGBsf_pZYjcsxvWGMp3aRc0hxttuse9Os-twV9sagL85JEIerGlVe46r4-HIvPqDXx-h14BtHfwZHEIeDJV02iD5hUkaXsgNZBXbObhLPfE0t3QNIVlnGmG9eHhzjC_HxTW7KDhAJFLI1FQddmCYfsIGo5F-km0v6sig-XaYbL8q2RaDImfHBs2dfjrS8IvpETf2WnufIAwpTuhAb2aUYkwyLnTPYYgtqvD1Uro63tpssTzQA8WYn0c1E0Xf1JnVCVpoqUqYK2sSiCPRRGZXONpjENQ-Ogk1cdZlC1vSv3B5le3U17ccvEtuyjSsNwAAAAGmRHBgAA
        sync: false
